name: Build Release

on:
  push:
    tags:
      - v[0-9].**
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled

jobs:
  build_python_wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd crates/python_rust_bridge/
          ./build.sh
